### ISSUE TITLE
template_before isn't called when records are skipped

### ISSUE THREAD

**Issue by phochste** [LibreCat/Catmandu-Template#6]
When the Fix script skips records, then the template_before (and template_after?) isn't called.

```
test.fix:
marc_map(020a,isbn.$append)  
select any_match(isbn.*,'^900')
```

Commandline:

```
$ catmandu convert MARC to Template --template_before head.xml --template body.xml --template_after foot.xml
```

This will show only body.xml if the first record was skipped.

**Comment by nics** [comment]
title should be "template_before isn't called when records are skipped"

**Comment by vpeil** [comment]
thanks @nics! #10 merged, so this one is solved.
